services:
  # Main REST API server
  api-server:
    image: kevinfham:test
    container_name: api-server
    network_mode: host
#    ports:
#      - "${SERVER_PORT:-3001}:${SERVER_PORT:-3001}"
    volumes:
      - './.env:/app/.env:ro'
      - './config.yml:/app/config.yml:ro'
      - './openssl/ca-cert.pem:/app/openssl/ca-cert.pem:ro'
      - './openssl/home-rest-api-cert.pem:/app/openssl/home-rest-api-cert.pem:ro'
      - './openssl/home-rest-api-cert.key:/app/openssl/home-rest-api-cert.key:ro'
    restart: always
#  nginx:
#    image: ghcr.io/nginxinc/nginx-unprivileged:stable-alpine
#    volumes:
#      - './nginx-config/api-server.conf:/etc/nginx/conf.d/default.conf:ro'
#    restart: always

#networks:
#  frontend: {}
#  backend: {}
